-- KB-01R5C OBSOLETE runtime probe
-- DO NOT RUN.
--
-- The earlier v0.1/v0.2 probe attempted more than one successful active-version
-- transition inside one SQL transaction. That is not representative of the n8n
-- runtime and conflicts with the deferred active-version integrity check.
--
-- KB-01R5C was verified on 2026-10-04 with separate committed executions:
--   Phase1: publish V1;
--   Phase2A: prepare ready V2/V3;
--   Phase2B: publish V2 and reject stale V3;
--   bot probe: qbit_test_bot active-only search;
--   guarded cleanup: remove exact synthetic rows.
--
-- Canonical evidence:
--   docs/evidence/KB-01/KB-01R5C_RUNTIME_VERIFIED_2026-10-04.md
--
-- No reusable mutating SQL is intentionally kept here because the successful
-- probes used run-specific UUIDs and have already been cleaned up.

SELECT 'KB-01R5C_OBSOLETE_DO_NOT_RUN' AS status;
